services:
  - type: web
    name: time-tracker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: time-tracker-db
          property: connectionString
      - key: PORT
        value: 8000

databases:
  - name: time-tracker-db
    plan: starter 